# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bysykkel < Formula
  desc "CLI for Oslo City Bike"
  homepage "https://github.com/staticaland/go-bysykkel"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/staticaland/go-bysykkel/releases/download/v0.1.0/go-bysykkel_0.1.0_darwin_arm64.tar.gz"
      sha256 "c41d5f7e73ce0bcfbb97eca254362d624aaa8102147140ecae2157d84171a020"

      def install
        bin.install "bysykkel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/staticaland/go-bysykkel/releases/download/v0.1.0/go-bysykkel_0.1.0_linux_arm64.tar.gz"
      sha256 "eb09b47ccea5f8558fc18d92803b1b6eeeff34f64901821e41261293e164edc8"

      def install
        bin.install "bysykkel"
      end
    end
  end
end
