# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bysykkel < Formula
  desc "CLI for Oslo City Bike"
  homepage "https://github.com/staticaland/go-bysykkel"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/staticaland/go-bysykkel/releases/download/v0.2.0/go-bysykkel_0.2.0_darwin_arm64.tar.gz"
      sha256 "9c72ae4fad56d1957d864cc0ac0a07db0c0cc15deb8f042950667ca140d2bb37"

      def install
        bin.install "bysykkel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/staticaland/go-bysykkel/releases/download/v0.2.0/go-bysykkel_0.2.0_linux_arm64.tar.gz"
      sha256 "27caf72fe0fc1a60d057725455c8b18e027aff053a35850a8216c14b779bce6d"

      def install
        bin.install "bysykkel"
      end
    end
  end
end
