name: Run

"on":
  workflow_dispatch: {}

jobs:

  run:

    name: Run bysykkel
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Setup Go environment
        uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: 1.19

      - name: Install CLI
        run: go install ./cmd/bysykkel

      - name: Run CLI
        run: bysykkel --help && bysykkel

      - name: Install server
        run: go install ./cmd/bysykkel-server

      - name: Run server
        run: bysykkel-server --help && bysykkel-server &

      - name: Query server
        run: curl localhost:4000/v1/stations

permissions:
  contents: read
